FROM debian:10

RUN apt-get update
RUN apt install -y python3 make xz-utils python3 python3-hamcrest \
  protobuf-compiler libprotobuf-dev zip libguava-java libprotobuf-java \
  flex bison libfl-dev pkg-config gcc g++ default-jdk-headless ninja-build

RUN useradd app
RUN mkdir -p /home/app
RUN chown app /home/app
USER app
WORKDIR /home/app

COPY --chown=app:app . .
