name: Autorelease

on:
  push:
    branches:
      - "master"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: python3-hamcrest protobuf-compiler libprotobuf-dev zip libguava-java libprotobuf-java flex bison libfl-dev

    - name: make
      run: make

    - name: date
      run: |
        echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

    - name: tag
      run: |
        git config user.name "davidgiven"
        git config user.email "dg@cowlark.com"
        git tag -f dev
        git push -f origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: delete-old-assets
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: dev
        assets: | 
          distribution.tar.xz
        fail-if-no-assets: false

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: Development build ${{ env.RELEASE_DATE }}
        files: |
          distribution.tar.xz
        tag_name: dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

